#!/bin/bash
# Type-checks the WinUI app's C# against the real Windows App SDK, in a container, in about
# ten seconds. Does not run the XAML compiler: markup errors still only show up in CI.
source "$(dirname "$0")/lib/common.sh"

command -v docker >/dev/null || die "docker is needed; this is the only WinUI check off Windows"

WORK="$(mktemp -d)"
trap 'rm -rf "$WORK"' EXIT

# The XAML compiler generates InitializeComponent and a field per x:Name. Standing those in
# is the whole trick: everything else in the code-behind then compiles against the real SDK.
python3 - "$REPO_ROOT" "$WORK" <<'PY'
import glob, os, re, sys

repo, work = sys.argv[1], sys.argv[2]
out = ["// Generated by scripts/check-winui.sh. Stands in for what the XAML compiler makes,",
       "// so the code-behind can be checked where WinUI's own XAML pass cannot run.",
       "using Microsoft.UI.Xaml;",
       "using Microsoft.UI.Xaml.Controls;",
       "",
       "namespace RedLine.App;",
       ""]
for path in sorted(glob.glob(os.path.join(repo, "windows/RedLine.App/*.xaml"))):
    text = open(path).read()
    named = re.search(r'x:Class="RedLine\.App\.(\w+)"', text)
    if not named:
        continue
    out.append(f"public partial class {named.group(1)}")
    out.append("{")
    out.append("    private void InitializeComponent() { }")
    for kind, name in re.findall(r'<(\w+)[^>]*?x:Name="(\w+)"', text, re.S):
        out.append(f"    internal {kind} {name} = null!;")
    out.append("}")
    out.append("")
open(os.path.join(work, "XamlStubs.cs"), "w").write("\n".join(out))
PY

# The package versions have to match RedLine.App.csproj, or this checks a different SDK than
# the one CI builds against, which is worse than not checking at all.
grep -q 'Microsoft.WindowsAppSDK" Version="1.8' "$REPO_ROOT/windows/RedLine.App/RedLine.App.csproj" \
    || die "the Windows App SDK version moved; update scripts/check-winui.sh to match"

cat > "$WORK/check.csproj" <<'EOF'
<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net9.0-windows10.0.19041.0</TargetFramework>
    <TargetPlatformMinVersion>10.0.17763.0</TargetPlatformMinVersion>
    <RootNamespace>RedLine.App</RootNamespace>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <EnableDefaultCompileItems>false</EnableDefaultCompileItems>
    <EnableMsixTooling>false</EnableMsixTooling>
    <EnableWindowsTargeting>true</EnableWindowsTargeting>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.WindowsAppSDK" Version="1.8.260804001" />
    <PackageReference Include="Microsoft.Windows.SDK.BuildTools" Version="10.0.26100.4948" />
    <PackageReference Include="H.NotifyIcon.WinUI" Version="2.3.2" />
    <PackageReference Include="System.Drawing.Common" Version="9.0.1" />
  </ItemGroup>
  <ItemGroup>
    <Compile Include="/repo/windows/RedLine.App/*.cs" />
    <Compile Include="/work/XamlStubs.cs" />
    <ProjectReference Include="/repo/windows/RedLine.Core/RedLine.Core.csproj" />
  </ItemGroup>
</Project>
EOF

info "Type-checking the WinUI code-behind against Windows App SDK 1.8"
# Compile only: the Build target then runs MakePri.exe, which is a Windows binary
docker run --rm -v "$REPO_ROOT":/repo -v "$WORK":/work -w /work \
    mcr.microsoft.com/dotnet/sdk:9.0 \
    dotnet build -t:Compile --nologo -v q \
    || die "the WinUI code-behind does not compile"

info "WinUI code-behind compiles. XAML markup is still only checked by CI."
