#!/bin/bash
# Embeds the statusline feeders into RedlineCore as string constants.
# Committed output, regenerable input: run this after editing either feeder script.
#
# Embedded rather than shipped as a resource because the command line tool is a single
# executable with no bundle beside it, and it has to be able to install the feeder on a
# machine that never saw this repository.
set -euo pipefail
cd "$(dirname "$0")/.."

OUT="Sources/RedlineCore/StatuslineScripts.swift"
python3 - "$OUT" <<'PY'
import pathlib, sys

out = pathlib.Path(sys.argv[1])
sources = {
    "posix": pathlib.Path("scripts/claude-statusline.sh"),
    "windows": pathlib.Path("scripts/claude-statusline.ps1"),
}

def literal(text):
    # The extra newline is not cosmetic: Swift drops the last one before the closing
    # delimiter, so without it the embedded copy loses the file's trailing newline and the
    # drift test fails for a difference nobody can see.
    for hashes in ("#", "##", "###", "####"):
        if f'"""{hashes}' not in text and f'{hashes}"""' not in text:
            return f'{hashes}"""\n{text}\n"""{hashes}'
    raise SystemExit("no safe raw-string delimiter for this content")

body = [
    "// The statusline feeders, embedded so the command line tool can install one on a machine",
    "// that never saw this repository. Generated by scripts/embed-statusline.sh;",
    "// StatuslineSetupTests fails if this and scripts/ have drifted.",
    "import Foundation",
    "",
    "enum StatuslineScripts {",
]
for name, path in sources.items():
    text = path.read_text()
    body.append(f"    static let {name} = {literal(text)}")
    body.append("")
body.append("}")
out.write_text("\n".join(body))
print(f"wrote {out} ({out.stat().st_size} bytes)")
PY
